services:
  postgis:
    image: postgis/postgis:latest
    container_name: postgis_container
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: taxi_availability
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data


  airflow-db:
    image: postgres:15
    container_name: airflow_postgres
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow_password
      POSTGRES_DB: airflow_db
    ports:
      - "5434:5432"
    volumes:
      - airflow_postgres_data:/var/lib/postgresql/data

  airflow:
    image: apache/airflow:2.7.2
    container_name: airflow
    restart: always
    depends_on:
      - airflow-db
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow_password@airflow-db:5432/airflow_db
      AIRFLOW__CORE__FERNET_KEY: 'your_fernet_key'
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: >
      bash -c "airflow db init && airflow webserver --port 8080 & airflow scheduler"

volumes:
  etl_postgres_data:
  airflow_postgres_data:
  postgis_data: